
package org.jboss.example.client;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.7-04/11/2011 03:11 PM(mockbuild)-
 * Generated source version: 2.0
 * 
 */
@WebFault(name = "BasicException", targetNamespace = "http://webservices.samples.jboss.org/")
public class BasicException_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private BasicException faultInfo;

    /**
     * 
     * @param message
     * @param faultInfo
     */
    public BasicException_Exception(String message, BasicException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param message
     * @param faultInfo
     * @param cause
     */
    public BasicException_Exception(String message, BasicException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: org.jboss.example.client.BasicException
     */
    public BasicException getFaultInfo() {
        return faultInfo;
    }

}
