
package org.jboss.example.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.7-04/11/2011 03:11 PM(mockbuild)-
 * Generated source version: 2.0
 * 
 */
@WebService(name = "HelloWorld", targetNamespace = "http://webservices.samples.jboss.org/")
public interface HelloWorld {


    /**
     * 
     * @param two
     * @param one
     * @param three
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "multipleArgs", targetNamespace = "http://webservices.samples.jboss.org/", className = "org.jboss.example.client.MultipleArgs")
    @ResponseWrapper(localName = "multipleArgsResponse", targetNamespace = "http://webservices.samples.jboss.org/", className = "org.jboss.example.client.MultipleArgsResponse")
    public String multipleArgs(
        @WebParam(name = "one", targetNamespace = "")
        String one,
        @WebParam(name = "two", targetNamespace = "")
        String two,
        @WebParam(name = "three", targetNamespace = "")
        String three);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     * @throws BasicException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "sayGoodBye", targetNamespace = "http://webservices.samples.jboss.org/", className = "org.jboss.example.client.SayGoodBye")
    @ResponseWrapper(localName = "sayGoodByeResponse", targetNamespace = "http://webservices.samples.jboss.org/", className = "org.jboss.example.client.SayGoodByeResponse")
    public String sayGoodBye(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        SomeRestrictedObject arg1)
        throws BasicException_Exception
    ;

}
